### ISSUE TITLE
PCBのデータについて

### ISSUE THREAD

**Issue by rk2kk** [kumamuk-git/roBa#1]
Ki CadでPCBデータを正常に開くことができません。（フットプリントが反転しているものがあります。）プロジェクトのデータがあるディレクトリごとアップロードお願いします。
参考　[keyballの例](https://github.com/Yowkees/keyball/tree/main/keyball39/design_data)

**Comment by kumamuk-git** [comment]
シンボルやフットプリントの追加、および各kicad_pcbファイルの修正を行いました。
別pcでリポジトリを落としてkicad_pcbファイルを開くと問題なく開くことができましたがいかがでしょうか。
もし改善しないようであれば、具体的にどのフットプリントが反転しているかを教えていただけますか？

**Comment by rk2kk** [comment]
シンボルとフットプリントの反映を確認しました。対応ありがとうございました。
フットプリントのプロパティ/位置/面がすべて表面になっているため、裏面実装のソケットやダイオードが3D表示やPCBAができません。（レイヤは正しいためPCBのみの発注で手はんだであれば問題ないと思います。）

**Comment by kumamuk-git** [comment]
センサ用基板以外はPCBAを前提としていないため、特に考慮していません。
PCBAサービスに発注の際は各自データを調整いただければと思います。
