### ISSUE TITLE
親指部分はCherry MX互換のスイッチで動作可能でしょうか？

### ISSUE THREAD

**Issue by sekai013** [kumamuk-git/roBa#2]
制作おつかれさまです。素晴らしいキーボードでぜひ購入したいと思っているのですが
ビルドガイドを読んでいてひとつ疑問に思ったので質問させてください。
ビルドガイドでは親指部分にはchoc用ソケットをはんだ付けするように書かれていますが
[写真](https://github.com/kumamuk-git/roBa/blob/main/doc/buildguide.md#3-1%E3%83%80%E3%82%A4%E3%82%AA%E3%83%BC%E3%83%89%E3%81%AE%E3%81%AF%E3%82%93%E3%81%A0%E4%BB%98%E3%81%91)を見る限りはKeyballのようにCherry MX用のソケットもはんだ付けできるように見えます。
Cherry MX用のソケットを個人で用意してはんだ付けすれば親指部分もCherry MX互換スイッチで動作させられるのでしょうか？

**Comment by kumamuk-git** [comment]
>親指部分もCherry MX互換スイッチで動作させられるのでしょうか？

→はい。keyballと同様Cherry MX互換ソケットを取り付け可能で動作します。
　ただ用意しているケースは親指部分を低くしているため、見た目上は合わないかもかもしれません。

**Comment by sekai013** [comment]
素早いご回答ありがとうございます！
